# Generated by Django 3.0.6 on 2022-02-06 01:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('winner', models.CharField(max_length=20, null=True)),
                ('winner_id', models.IntegerField(null=True)),
                ('pred_all', models.FloatField(null=True)),
                ('pred_tip', models.FloatField(null=True)),
                ('pred_base', models.FloatField(null=True)),
                ('pred_none', models.FloatField(null=True)),
                ('model', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
