# Generated by Django 3.0.6 on 2022-05-29 01:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('heatmap_plot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='heatmap_plot')),
            ],
        ),
    ]
